version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./debug/Dockerfile
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    container_name: server
    environment:
      - DEBUG=True
      - USERDOMAIN=${USERDOMAIN}
    depends_on:
      - pg
    ports:
      - "8080:8080"
      - "40000:40000"
  pg:
    image: postgres:latest
    container_name: clair_postgres
    environment:
      POSTGRES_PASSWORD: 1