# docker run --rm --name pg -e POSTGRES_PASSWORD=1 -d -p 5432:5432 -v $HOME/docker/volumes/postgres://var/lib/postgresql/data --net outyet-net  postgres
# docker run -d -p 5000:8080 --name test --rm --net outyet-net outyet
version: "3"
services:
  server:
    # image: outyet
    build: .
    environment:
      - DEBUG=True
      - USERDOMAIN=${USERDOMAIN}
    depends_on:
      - pg
#    ports:
#      - "8080:5000"
  pg:
    image: postgres:latest
    container_name: clair_postgres
    environment:
      POSTGRES_PASSWORD: 1
#    ports:
#      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data
#volumes:
#  db-data: