version: "3"
services:
  server:
    build:
      dockerfile: ./config/debug/Dockerfile
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    container_name: server
    environment:
      - DEBUG=True
    ports:
      - "40000:40000"